name: "Matrix Heisenbridge & Webmail, with Wireguard"
description: >-
  Wireguard, IRC bridge for Matrix, and webmail. Intended for use with work's VPN to assist with work communications
url: "https://github.com/mijofa/hassio-addons/wireguard_heisenbridge_webmail"
version: "0.0.1"
slug: "wireguard_heisenbridge_webmail"
ingress: true
# ingress_port: 80
# ingress_entry: index.php
ingress_stream: true
panel_icon: mdi:email-multiple
# panel_icon: mdi:mailbox
# panel_icon: mdi:at
panel_title: Email
arch:
  # - aarch64
  - amd64
  # - armhf
  # - armv7
  # - i386

# These are needed for Wireguard config
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun

map:
  # Move the appservice registration.yaml file here so that the synapse container can see it
  - share:rw
schema:
  heisenbridge:
    synapse_url: str
    own_url: str
    owner_mxid: str

  wireguard:
    own_IP: str
    private_key: password

    endpoint: str
    public_key: str
    allowed_IPs: str
options:
  heisenbridge:
    synapse_url: http://674b3982-matrixdotorg-synapse:8008/
    own_url: http://674b3982-wireguard-heisenbridge-webmail:9898/
    owner_mxid: null

  wireguard:
    own_IP: null
    private_key: null
    endpoint: null
    public_key: null
    allowed_IPs: null
