name: "Matrix Heisenbridge & Webmail, with Wireguard"
description: >-
  Wireguard, IRC bridge for Matrix, and webmail. Intended for use with work's VPN to assist with work communications
url: "https://github.com/mijofa/hassio-addons/wireguard_heisenbridge_webmail"
version: "0.0.1"
slug: "wireguard_heisenbridge_webmail"
ingress: true
# ingress_port: 80
# ingress_entry: index.php
ingress_stream: true
panel_icon: mdi:email-multiple
# panel_icon: mdi:mailbox
# panel_icon: mdi:at
panel_title: Email
arch:
  # - aarch64
  - amd64
  # - armhf
  # - armv7
  # - i386

# These are needed for Wireguard config
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun

map:
  # Move the appservice registration.yaml file here so that the synapse container can see it
  - share:rw
schema:
  heisenbridge_synapse_url: str
  heisenbridge_own_url: str
  heisenbridge_owner_mxid: str

  wireguard_own_IP: str
  wireguard_private_key: password

  wireguard_endpoint: str
  wireguard_public_key: str
  wireguard_allowed_IPs: [str]

  muttrc: [str]
options:
  heisenbridge_synapse_url: http://674b3982-matrixdotorg-synapse:8008/
  heisenbridge_own_url: http://674b3982-wireguard-heisenbridge-webmail:9898/
  heisenbridge_owner_mxid: null

  wireguard_own_IP: null
  wireguard_private_key: null
  wireguard_endpoint: null
  wireguard_public_key: null
  wireguard_allowed_IPs: null

  muttrc: []
