name: "Matrix Heisenbridge, with Wireguard"
description: >-
  Add-on wrapper for hif1/heisenbridge, with included Wireguard support. Intended for use with work's VPN to assist with work communications
url: "https://github.com/mijofa/hassio-addons/tree/master/hif1-heisenbridge_wireguard"
version: "0.7.0"
slug: "hif1-heisenbridge_wireguard"
arch:
  # - aarch64
  - amd64
  # - armhf
  # - armv7
  # - i386

# These are needed for Wireguard config
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun

map:
  # Move the appservice registration.yaml file here so that the synapse container can see it
  - share:rw
schema:
  heisenbridge_synapse_url: url
  heisenbridge_own_url: url
  heisenbridge_owner_mxid: str

  wireguard_own_IP: str
  wireguard_private_key: password
  wireguard_endpoint: str
  wireguard_public_key: str
  wireguard_allowed_IPs: [str]
options:
  heisenbridge_synapse_url: http://674b3982-matrixdotorg-synapse:8008/
  heisenbridge_own_url: http://674b3982-hif1-heisenbridge-wireguard:9898/
  heisenbridge_owner_mxid: null

  wireguard_own_IP: null
  wireguard_private_key: null
  wireguard_endpoint: null
  wireguard_public_key: null
  wireguard_allowed_IPs: null
