name: "Cypht"
description: >-
  Wrapper for the official Cypht container
url: "https://github.com/jasonmunro/cypht/"
version: "0.0.1"
slug: "cypht"
ingress: true
ingress_port: 80
# ingress_entry: index.php
# ingress_stream: true
# panel_icon: mdi:email-multiple
panel_icon: mdi:mailbox
# panel_icon: mdi:at
panel_title: Email
arch:
  # - aarch64
  - amd64
  # - armhf
  # - armv7
  # - i386
schema:
  CYPHT_SESSION_TYPE: str?
  CYPHT_AUTH_TYPE: str?
  CYPHT_AUTH_USERNAME: str?
  CYPHT_AUTH_PASSWORD: str?
  CYPHT_LDAP_AUTH_SERVER: str?
  CYPHT_LDAP_AUTH_PORT: str?
  CYPHT_LDAP_AUTH_TLS: str?
  CYPHT_LDAP_AUTH_BASE_DN: str?
  CYPHT_IMAP_AUTH_NAME: str?
  CYPHT_IMAP_AUTH_SERVER: str?
  CYPHT_IMAP_AUTH_PORT: str?
  CYPHT_IMAP_AUTH_TLS: str?
  CYPHT_POP3_AUTH_NAME: str?
  CYPHT_POP3_AUTH_SERVER: str?
  CYPHT_POP3_AUTH_PORT: str?
  CYPHT_POP3_AUTH_TLS: str?
  CYPHT_DEFAULT_SMTP_NAME: str?
  CYPHT_DEFAULT_SMTP_SERVER: str?
  CYPHT_DEFAULT_SMTP_PORT: str?
  CYPHT_DEFAULT_SMTP_TLS: str?
  CYPHT_DEFAULT_SMTP_NO_AUTH: str?
  CYPHT_USER_CONFIG_TYPE: str?
  CYPHT_USER_SETTINGS_DIR: str?
  CYPHT_ATTACHMENT_DIR: str?
  CYPHT_APP_DATA_DIR: str?
  CYPHT_DISABLE_ORIGIN_CHECK: str?
  CYPHT_ADMIN_USERS: str?
  CYPHT_COOKIE_DOMAIN: str?
  CYPHT_DEFAULT_EMAIL_DOMAIN: str?
  CYPHT_REDIRECT_AFTER_LOGIN: str?
  CYPHT_APP_NAME: str?
  CYPHT_DEFAULT_LANGUAGE: str?
  CYPHT_JS_COMPRESS: str?
  CYPHT_CSS_COMPRESS: str?
  CYPHT_ENABLE_MEMCACHED: str?
  CYPHT_MEMCACHED_SERVER: str?
  CYPHT_MEMCACHED_PORT: str?
  CYPHT_MEMCACHED_AUTH: str?
  CYPHT_MEMCACHED_USER: str?
  CYPHT_MEMCACHED_PASS: str?
  CYPHT_ALLOW_LONG_SESSION: str?
  CYPHT_LONG_SESSION_LIFETIME: str?
  CYPHT_ENCRYPT_AJAX_REQUESTS: str?
  CYPHT_ENCRYPT_LOCAL_STORAGE: str?
  CYPHT_DISABLE_IP_CHECK: str?
  CYPHT_ALLOW_EXTERNAL_IMAGE_SOURCES: str?
  CYPHT_SINGLE_SERVER_MODE: str?
  CYPHT_DISABLE_EMPTY_SUPERGLOBALS: str?
  CYPHT_DISABLE_OPEN_BASEDIR: str?
  CYPHT_DISABLE_INI_SETTINGS: str?
  CYPHT_DISABLE_FINGERPRINT: str?
  CYPHT_DB_URL: str?
  CYPHT_DB_CONNECTION_TYPE: str?
  CYPHT_DB_HOST: str?
  CYPHT_DB_SOCKET: str?
  CYPHT_DB_NAME: str?
  CYPHT_DB_USER: str?
  CYPHT_DB_PASS: str?
  CYPHT_DB_DRIVER: str?
  CYPHT_MODULE_CORE: str?
  CYPHT_MODULE_CONTACTS: str?
  CYPHT_MODULE_LOCAL_CONTACTS: str?
  CYPHT_MODULE_LDAP_CONTACTS: str?
  CYPHT_MODULE_GMAIL_CONTACTS: str?
  CYPHT_MODULE_FEEDS: str?
  CYPHT_MODULE_POP3: str?
  CYPHT_MODULE_IMAP: str?
  CYPHT_MODULE_2FA: str?
  CYPHT_MODULE_SMTP: str?
  CYPHT_MODULE_ACCOUNT: str?
  CYPHT_MODULE_IDLE_TIMER: str?
  CYPHT_MODULE_CALENDAR: str?
  CYPHT_MODULE_THEMES: str?
  CYPHT_MODULE_NUX: str?
  CYPHT_MODULE_DEVELOPER: str?
  CYPHT_MODULE_GITHUB: str?
  CYPHT_MODULE_RECAPTCHA: str?
  CYPHT_MODULE_WORDPRESS: str?
  CYPHT_MODULE_HISTORY: str?
  CYPHT_MODULE_SAVED_SEARCHES: str?
  CYPHT_MODULE_NASA: str?
  CYPHT_MODULE_PROFILES: str?
  CYPHT_MODULE_INLINE_MESSAGE: str?
  CYPHT_MODULE_IMAP_FOLDERS: str?
  CYPHT_MODULE_KEYBOARD_SHORTCUTS: str?
  CYPHT_MODULE_SITE: str?
  CYPHT_MODULE_DYNAMIC_LOGIN: str?
  CYPHT_MODULE_API_LOGIN: str?
  CYPHT_API_LOGIN_KEY: str?
  CYPHT_MODULE_RECOVER_SETTINGS: str?
  CYPHT_MODULE_HELLO_WORLD: str?
  CYPHT_MODULE_DESKTOP_NOTIFICATIONS: str?
  CYPHT_DEFAULT_SETTING_NO_PASSWORD_SAVE: str?
  CYPHT_DEFAULT_SETTING_IMAP_PER_PAGE: str?
  CYPHT_DEFAULT_SETTING_SIMPLE_MSG_PARTS: str?
  CYPHT_DEFAULT_SETTING_MSG_PART_ICONS: str?
  CYPHT_DEFAULT_SETTING_TEXT_ONLY: str?
  CYPHT_DEFAULT_SETTING_SENT_PER_SOURCE: str?
  CYPHT_DEFAULT_SETTING_SENT_SINCE: str?
  CYPHT_DEFAULT_SETTING_SHOW_LIST_ICONS: str?
  CYPHT_DEFAULT_SETTING_START_PAGE: str?
  CYPHT_DEFAULT_SETTING_DISABLE_DELETE_PROMPT: str?
  CYPHT_DEFAULT_SETTING_NO_FOLDER_ICONS: str?
  CYPHT_DEFAULT_SETTING_ALL_EMAIL_PER_SOURCE: str?
  CYPHT_DEFAULT_SETTING_ALL_EMAIL_SINCE: str?
  CYPHT_DEFAULT_SETTING_ALL_SINCE: str?
  CYPHT_DEFAULT_SETTING_ALL_PER_SOURCE: str?
  CYPHT_DEFAULT_SETTING_UNREAD_PER_SOURCE: str?
  CYPHT_DEFAULT_SETTING_FLAGGED_PER_SOURCE: str?
  CYPHT_DEFAULT_SETTING_FLAGGED_SINCE: str?
  CYPHT_DEFAULT_SETTING_UNREAD_SINCE: str?
  CYPHT_DEFAULT_SETTING_TIMEZONE: str?
  CYPHT_DEFAULT_SETTING_LIST_STYLE: str?
  CYPHT_DEFAULT_SETTING_LANGUAGE: str?
  CYPHT_DEFAULT_SETTING_UNREAD_EXCLUDE_FEEDS: str?
  CYPHT_DEFAULT_SETTING_FEED_LIMIT: str?
  CYPHT_DEFAULT_SETTING_FEED_SINCE: str?
  CYPHT_DEFAULT_SETTING_SMTP_COMPOSE_TYPE: str?
  CYPHT_DEFAULT_SETTING_SMTP_AUTO_BCC: str?
  CYPHT_DEFAULT_SETTING_THEME: str?
  CYPHT_DEFAULT_SETTING_UNREAD_EXCLUDE_WORDPRESS: str?
  CYPHT_DEFAULT_SETTING_WORDPRESS_SINCE: str?
  CYPHT_DEFAULT_SETTING_UNREAD_EXCLUDE_GITHUB: str?
  CYPHT_DEFAULT_SETTING_GITHUB_LIMIT: str?
  CYPHT_DEFAULT_SETTING_GITHUB_SINCE: str?
  CYPHT_DEFAULT_SETTING_INLINE_MESSAGE: str?
  CYPHT_DEFAULT_SETTING_ENABLE_KEYBOARD_SHORTCUTS: str?
