name: "google-find-hub"
description: "Google Find Hub"
version: "0.2"
slug: "googlefindhub"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
audio: false
hassio_api: false
homeassistant_api: false
# hassio_role: manager  # Only needed to instruct HA to reload the audio config
startup: services
boot: auto
ingress: false
schema:
  polling_interval_mins: int
  mqtt_host: str
  mqtt_port: int
options:
  polling_interval_mins: 15
  mqtt_host: supervisor
  mqtt_port: 1883
