name: "Mautrix Meta bridge"
description: >-
  Pretty bare-bones add-on wrapper for the dock.mau.dev/mautrix/meta container
url: "https://mau.dev/mautrix/meta"
version: "0.0.7"
slug: "mautrix-meta"
arch:
  # - aarch64
  - amd64
  # - armhf
  # - armv7
  # - i386
map:
  # Move the appservice registration.yaml file here so that the synapse container can see it
  - share:rw
#  # Makes sense to store the signing key in /ssl
#  - ssl:ro
#  # Better spot for storing the media files
schema:
  matrix_domain: str
  database_url: url
  synapse_url: url
  own_url: url

  double_puppet_token: password

  config.yaml: str
options:
  matrix_domain: null
  database_url: null
  synapse_url: http://674b3982-matrixdotorg-synapse:8008/
  own_url: http://674b3982-mautrix-meta:29319/

  double_puppet_token: ""

  # Copied from https://github.com/mautrix/meta/blob/3726a72b31dd4d1ef20c83cc9884b0ff499ccc4e/pkg/connector/example-config.yaml
  # FIXME: Pretty sure all of this config.yaml template is just bullshit at this point
  config.yaml: |
    # Which service is this bridge for? Available options:
    # * unset - allow users to pick any service when logging in (except facebook-tor)
    # * facebook - connect to FB Messenger via facebook.com
    # * facebook-tor - connect to FB Messenger via facebookwkhpilnemxj7asaniu7vnjjbiltxjqhye3mhbshg7kx5tfyd.onion
    #                  (note: does not currently proxy media downloads)
    # * messenger - connect to FB Messenger via messenger.com (can be used with the facebook side deactivated)
    # * instagram - connect to Instagram DMs via instagram.com
    #
    # Remember to change the appservice id, bot profile info, bridge username_template and management_room_text too.
    mode:

    # When in Instagram mode, should the bridge connect to WhatsApp servers for encrypted chats?
    # In FB/Messenger mode encryption is always enabled, this option only affects Instagram mode.
    ig_e2ee: false

    # Displayname template for FB/IG users. Available variables:
    #  .DisplayName - The display name set by the user.
    #  .Username - The username set by the user.
    #  .ID - The internal user ID of the user.
    displayname_template: '{{or .DisplayName .Username "Unknown user"}}'

    # Static proxy address (HTTP or SOCKS5) for connecting to Meta.
    proxy:
    # HTTP endpoint to request new proxy address from, for dynamically assigned proxies.
    # The endpoint must return a JSON body with a string field called proxy_url.
    get_proxy_from:
    # Should media be proxied too?
    proxy_media: false
    # Minimum interval between full reconnects in seconds, default is 1 hour
    min_full_reconnect_interval_seconds: 3600
    # Interval to force refresh the connection (full reconnect), default is 20 hours. Set 0 to disable force refreshes.
    force_refresh_interval_seconds: 72000
    # Disable fetching XMA media (reels, stories, etc) when backfilling.
    disable_xma_backfill: true
    # Disable fetching XMA media entirely.
    disable_xma_always: false
