name: "snapcast-client"
version: "1.0"
slug: "snapcastclient"
init: false
description: "Snapcast client"
startup: "services"
boot: auto
audio: true
options:
  snapclientopts: "-h snapcastserver"
schema:
  snapclientopts: str
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
args:
  ALSA_VERSION: 1.2.5.1
  PULSE_VERSION: 14.2
