name: "Matrix.org Synapse"
description: >-
  Pretty bare-bones add-on wrapper for the matrixdotorg/synapse Dockerhub container
url: "https://hub.docker.com/r/matrixdotorg/synapse"
version: "0.0.19"
slug: "matrixdotorg-synapse"
ingress: true
ingress_port: 8008
ingress_entry: _matrix/static/
ingress_stream: true
panel_icon: mdi:forum
panel_title: Matrix
watchdog: http://[HOST]:8008/_matrix/client/versions
arch:
  # - aarch64
  - amd64
  # - armhf
  # - armv7
  # - i386
map:
  # Makes sense to store the signing key in /ssl
  - ssl:ro
  # Better spot for storing the media files
  - share:rw
schema:
  server_name: str
  public_baseurl: url
  database_url: url
  autofill_appservices: bool
  shared_secret_auth: password?
  default_user: str?
  default_userpass: password?

  media_store_path: str?

  registration_shared_secret: password?
  macaroon_secret_key: password?

  homeserver.yaml: str
options:
  server_name: null
  public_baseurl: null

  database_url: 'sqlite:///data/homeserver.db'
  # Sample for postgres use with TimescaleDB add-on from https://github.com/Expaso/hassos-addons/tree/master/timescaledb:
  #     'postgres://synapse:CorrectBatteryHorseStaple@77b2833f-timescaledb/synapse?cp_min=5&cp_max=10'
  # That requires first creating the user & database though:
  #      apk add postgresql14-client
  #      psql --host=77b2833f-timescaledb --user postgres -c "DO \$\$ begin IF EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'synapse') THEN RAISE NOTICE 'Synapse role already exists. Skipping.'; ELSE CREATE ROLE synapse WITH PASSWORD 'CorrectBatteryHorseStaple' LOGIN; END IF; end \$\$"
  #      psql --host=77b2833f-timescaledb --user postgres -c  "CREATE DATABASE synapse LOCALE = 'C' ENCODING = 'UTF8' TEMPLATE = 'template0' OWNER = 'synapse'"

  autofill_appservices: true

  shared_secret_auth: ""

  default_user: null
  default_userpass: "CorrectBatteryHorseStaple"

  media_store_path: "/share/matrix_media"


  #registration_shared_secret: ""
  #macaroon_secret_key: ""

  homeserver.yaml: |
    ### This is largely copied directly from the default /conf/homeserver.yaml template,
    ## Server ##
    server_name: {server_name}
    pid_file: /homeserver.pid
    web_client: False
    soft_file_limit: 0
    log_config: "/data/{server_name}.log.config"
    public_baseurl: {public_baseurl}
    serve_server_wellknown: true

    ## Ports ##
    listeners:
      - port: 8008
        tls: false
        bind_addresses: ['::']
        type: http
        x_forwarded: true
        resources:
          - names: [client]
            compress: true
          - names: [federation]
            compress: false

    ## Database ##
    database: "Autogenerated by startup scripts"

    ## Performance ##
    event_cache_size: "10K"

    ## Ratelimiting ##
    rc_messages_per_second: 0.2
    rc_message_burst_count: 10.0
    federation_rc_window_size: 1000
    federation_rc_sleep_limit: 10
    federation_rc_sleep_delay: 500
    federation_rc_reject_limit: 50
    federation_rc_concurrent: 3

    ## Files ##
    media_store_path: {media_store_path}
    max_upload_size: "50M"
    max_image_pixels: "32M"
    dynamic_thumbnails: false
    # List of thumbnail to precalculate when an image is uploaded.
    thumbnail_sizes:
    - width: 32
      height: 32
      method: crop
    - width: 96
      height: 96
      method: crop
    - width: 320
      height: 240
      method: scale
    - width: 640
      height: 480
      method: scale
    - width: 800
      height: 600
      method: scale
    url_preview_enabled: False
    max_spider_size: "10M"

    ## Registration ##
    enable_registration: False
    registration_shared_secret: {registration_shared_secret}
    bcrypt_rounds: 12
    allow_guest_access: False
    enable_group_creation: true

    ## Metrics ###
    # enable_metrics: True
    # report_stats: True
    enable_metrics: False
    report_stats: False

    ## API Configuration ##
    app_service_config_files: "Autogenerated by startup scripts"
    # FIXME: What actually is this? Removing it doesn't make things crash, so I think just remove it.
    macaroon_secret_key: {macaroon_secret_key}
    expire_access_token: False

    ## Signing Keys ##
    signing_key_path: "/ssl/{server_name}.signing.key"
    old_signing_keys: {{}}
    key_refresh_interval: "1d" # 1 Day.

    # The trusted servers to download signing keys from.
    trusted_key_servers:
      - server_name: matrix.org
        verify_keys:
          "ed25519:auto": "Noi6WqcDj0QmPxCNQqgezwTlBKrfqehY1u2FyWP9uYw"  # Public key, *not* a secret

    password_config:
       enabled: true

    # Use this if some appservice's stop working during upgrade.
    # use_appservice_legacy_authorization: true

## Possible environment variables
# Mandatory config options:
# * SYNAPSE_SERVER_NAME
# * SYNAPSE_REPORT_STATS
# Known optional config options:
# * SYNAPSE_WORKER
# * SYNAPSE_CONFIG_DIR  # Should stay with default /data
# * SYNAPSE_CONFIG_PATH  # Should stay with default $SYNAPSE_CONFIG_DIR/homeserver.yaml
# * SYNAPSE_DATA_DIR  # Should stay with default /data
# * SYNAPSE_REGISTRATION_SHARED_SECRET  # DO NOT set this
# * SYNAPSE_ENABLE_REGISTRATION  # DO set this
# * SYNAPSE_MACAROON_SECRET_KEY  # DO NOT set this
# * SYNAPSE_HTTP_PORT  # default 8008
# * SYNAPSE_EVENT_CACHE_SIZE  # default '10K'
# * SYNAPSE_MAX_UPLOAD_SIZE  # default '50M'
# * SYNAPSE_ALLOW_GUEST  # default False
# * SYNAPSE_LOG_LEVEL  # Beware of setting this to DEBUG as that will put sensitive info in the logs
# * LOG_FILE_PATH  # Don't bother messing with this, the logs go out on the console anyway
# * SYNAPSE_LOG_SENSITIVE  # DO NOT set this, it lets sensitive info get into the logs
# * SYNAPSE_NO_TLS
# Recaptcha
# * SYNAPSE_RECAPTCHA_PUBLIC_KEY
# * SYNAPSE_RECAPTCHA_PRIVATE_KEY
# TURN
# * SYNAPSE_TURN_URIS
# * SYNAPSE_TURN_SECRET
# # Only for Postgres support
# * POSTGRES_PASSWORD
# * POSTGRES_USER  # default 'synapse'
# * POSTGRES_DB  # default 'synapse'
# * POSTGRES_HOST  # default 'db'
# * POSTGRES_PORT  # default '5432'
