name: "Matrix.org Synapse"
description: "Pretty bare-bones add-on wrapper for the matrixdotorg/synapse Dockerhub container"
url: "https://hub.docker.com/r/matrixdotorg/synapse"
version: "0.0.1"
slug: "mijofa-matrixdotorg-synapse"
arch:
#  - aarch64
  - amd64
#  - armhf
#  - armv7
#  - i386
# Literally just put this here so that I can see if that creates a /data filesystem for me
options:
  foo:
    bar: "baz"
schema:
  foo:
    bar: str
