name: "Matrix.org Synapse"
description: "Pretty bare-bones add-on wrapper for the matrixdotorg/synapse Dockerhub container"
url: "https://hub.docker.com/r/matrixdotorg/synapse"
version: "0.0.1"
slug: "mijofa-matrixdotorg-synapse"
arch:
#  - aarch64
  - amd64
#  - armhf
#  - armv7
#  - i386
