external_components:
  # https://github.com/esphome/esphome/pull/14389
  - source: github://pr#14389
    components: [ snapclient, media_player ]
    refresh: 1d
  # - source: github://mijofa/esphome-luar123-snapclient@snapclient2
  #   components: [ snapclient, media_player ]
  #   refresh: 0s

# ============================================================================
# ESP32 Hardware Configuration
# ============================================================================
esp32:
  framework:
    type: esp-idf

# Main ref: https://community.home-assistant.io/t/solved-esphome-media-player-with-m5stack-spk-kit-and-atoms3-lite/784663
i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin: ${i2s_lrclk_pin}
    i2s_bclk_pin: ${i2s_bclk_pin}
    i2s_mclk_pin: ${i2s_mclk_pin}

# Uncomment this section for sendspin instead of snapcast
# FIXME: Barely tested
# speaker:
#   - platform: i2s_audio
#     id: i2s_speaker
#     i2s_audio_id: i2s_audio_bus
#     i2s_dout_pin: ${i2s_dout_pin}
#     # i2s_dout_pin: GPIO5
#     dac_type: external
#     audio_dac: es8311_dac
#     sample_rate: 48000
#     channel: left
# ...#33-media-player-configuration
# sendspin:
# media_source:
#   - platform: sendspin
#     id: sendspin_media_source
#     buffer_size: 25000
# media_player:
#   - platform: speaker_source
#     id: external_media_player
#     name: Media Player
#     volume_min: 0.5
#     volume_max: 0.8
#     media_pipeline:
#       speaker: i2s_speaker
#       format: FLAC
#       sample_rate: "48000"
#       num_channels: "1"
#       sources:
#         - sendspin_media_source


# Uncomment this section for snapcast instead of sendspin
media_player:
  - platform: snapclient
    # Don't show up in Home Assistant, because Home Assistant can't really do anything with it anyway.
    # FIXME: Is it possible to associate the snapcast player with this device?
    internal: true
    id: snapclient_media_player
    hostname: ${snapserver_hostname}
    # port: 1704  # default
    name: ${friendly_name}
    i2s_dout_pin: ${i2s_dout_pin}
    on_play:
      - logger.log: "Playback started!"
    on_pause:
      - logger.log: "Playback paused!"
    on_idle:
      - logger.log: "Playback finished!"
    on_state:
      - logger.log: "Playback State change!"
