esphome:
  name: m5stack-atom-echos3r
  friendly_name: M5Stack Atom Echo S3R

api:
  encryption:
    key: [redacted]

ota:
  - platform: esphome
    password: [redacted]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: DEBUG

## M5Stack stuff
## ref: https://github.com/m5stack/esphome-yaml/blob/main/common/atom-echos3r-satellite-base.yaml
esp32:
  variant: esp32s3
  flash_size: 8MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    ## Note: Disable these configurations if you face the boot loop issue.
    sdkconfig_options:
        CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
        CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
        CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB: "y"

psram:
  mode: octal
  speed: 80MHz
  disabled: true

# I2C Bus Configuration
i2c:
  sda:
    number: GPIO45
    ignore_strapping_warning: true
  scl:
    number: GPIO0
    ignore_strapping_warning: true
  scan: false
  id: i2c0

# I2S Bus Configuration
i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin:
      number: GPIO3
      ignore_strapping_warning: true
    i2s_bclk_pin: GPIO17
    i2s_mclk_pin: GPIO11

audio_dac:
  - platform: es8311
    id: es8311_dac
    bits_per_sample: 16bit
    sample_rate: 48000

# microphone:
#   - platform: i2s_audio
#     id: i2s_mic
#     sample_rate: 16000
#     i2s_din_pin: GPIO4
#     bits_per_sample: 16bit
#     adc_type: external

speaker:
  - platform: i2s_audio
    id: i2s_speaker
    i2s_dout_pin: GPIO48
    dac_type: external
    sample_rate: 48000
    bits_per_sample: 16bit
    channel: left
    audio_dac: es8311_dac
    # FIXME: How much higher can we get before things fail?
    # The default (500ms) resulted in the speaker never being properly enabled.
    # I think this and sendspin were fighting for memory and ran out.
    # 250ms caused a few errors when first hitting play, logs indicate it recovers, but no sound comes out.
    buffer_duration: 100ms

# ## M5Stack stuff
# ## ref: https://docs.m5stack.com/en/homeassistant/voice_assistant/atom_echos3r_voice_assistant
# # Add the external package here
# packages:
#   remote_package_files:
#     url: https://github.com/m5stack/esphome-yaml
#     files: [common/atom-echos3r-satellite-base.yaml]
#     ref: main
#     refresh: 0s

# M5Stack upstream marked this as internal and used it in some scripting.
# I've decided to make this visible to Home Assistant, but don't know how I'll use it.
switch:
  - platform: gpio
    name: Speaker Enable
    pin: GPIO18
    # Upstream had this set to RESTORE_DEFAULT_ON, that was a little confusing because it was hard to tell whether it booted successfully.
    restore_mode: ALWAYS_ON
    entity_category: config
    disabled_by_default: true
    internal: false

# FIXME: Making this **AND** voice assistant stuff work requires copy/pasting pretty much all of the external package above.
## Spinsend stuff
## ref: https://github.com/el-bakkali/esp32-a1s-sendspin/blob/main/esp32-a1s.yaml#L198
sendspin:
  id: sendspin_hub
  task_stack_in_psram: false

media_source:
  - platform: sendspin
    id: sendspin_source
    # NOTE: This defaults to psram, I want to ensure this works on hardware without that.
    decode_memory: internal
    task_stack_in_psram: false
    # Don't know if this matters, but I've set it in sync with is2_audio above
    sample_rate: 48000
    # The default buffer size is 1000000, which is significantly higher than 250000, so don't use that
    # A buffer size of 250000 or more boots correctly, but sendspin fails to startup with no helpful description whatsoever
    # A buffer size of 200000 causes errors on boot and the device falls back to fallback boot of previous partition.
    # A buffer size of 150000 boots correctly, without sendspin errors, until playback is attempted, at which point I get these errors:
    # > i2s_common: i2s_alloc_dma_desc(541): allocate DMA buffer failed
    # > i2s_std: i2s_std_set_slot(138): allocate memory for dma descriptor failed
    # > i2s_std: i2s_channel_init_std_mode(327): initialize channel failed while setting slot
    # The minimum esphome will allow is 25000, so let's see how this goes
    # FIXME: How much higher can we get before things fail?
    buffer_size: 25000

media_player:
  - platform: speaker_source
    id: sendspin_media_player
    name: Sendspin Media Player
    media_pipeline:
      speaker: i2s_speaker
      sources:
        - sendspin_source
